name: backend
registry: tuskkdev
services:
- name: backend-api-core
  project: srcs\Backend.Api\Backend.Api.csproj
  bindings:
    - port: 6661
  env:
    - name: JWT_EXPIRY_TIME_IN_HOURS
      value: 1  
    - name: JWT_SIGNATURE_KEY
      value: 123456789
- name: backend-api-db
  project: srcs\Backend.Api.Database\Backend.Api.Database.csproj
  bindings:
    - port: 7771
  env:
    - name: PGSQL_DATABASE_USERNAME
      value: postgres
    - name: PGSQL_DATABASE_PASSWORD
      value: postgres
    - name: PGSQL_DATABASE_NAME
      value: postgres
    - name: PGSQL_DATABASE_ENCRYPTION_KEY
      value: AAECAwQFBgcICQoLDA0ODw==
    - name: PGSQL_DATABASE_ENCRYPTION_KEY
      value: AAECAwQFBgcICQoLDA0ODw==
- name: backend-api-auth
  project: srcs\Backend.Api.Authentication\Backend.Api.Authentication.csproj
  bindings:
    - port: 8881
- name: backend-rabbitmq-server
  project: srcs\Backend.Server.RabbitMQ\Backend.Server.RabbitMQ.csproj
  bindings:
    - port: 9991
  env:
    - name: RABBITMQ_PASSWORD
      value: user
    - name: RABBITMQ_USERNAME
      value: bitnami
- name: postgres
  image: postgres:latest
  bindings:
    - port: 5432
  env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
- name: redis
  image: redis:latest
  bindings:
    - port: 6379
      connectionString: "${host}:${port}"
  env:
    - name: REDIS_PASSWORD
      value: redis
- name: rabbitmq
  image: bitnami/rabbitmq:latest
  bindings:
    - port: 5672
  env:
    - name: RABBITMQ_PASSWORD
      value: root
    - name: RABBITMQ_USERNAME
      value: root